# Generated by Django 3.2.5 on 2021-07-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voteEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('voteEvent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voteEvent.voteevent')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
